name: github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.74.3
          TARGET_REPO: buildupdevs/buildupdevs.github.io/website
          TOKEN: ${{ secrets.TOKEN }}
